# CS240 : Principle of Data Science
## <u>Assignment#03</u>: Data Cleansing
### (100 คะแนน)

We will use the Hotel Booking Demand dataset from the Kaggle.
The data file [``hotel_booking.csv``](https://drive.google.com/file/d/1jusIlLhFvfNnHAodzjx3M_x1sukpAvss/view?usp=drive_link)
has been attached to this assignment.
This data set contains booking information for a *city hotel* and a *resort hotel* and includes information such as when the booking was made, lead time, length of stay, the number of adults, children, and/or babies, and the number of available parking spaces, among other things. Descriptions for every column in the data set has made available with this assignment as well.

####1. (1 คะแนน) Import Required Packages

Bring in all the required packages.

In [601]:
#Q.1.
from google.colab import drive
from pathlib import Path
import pandas as pd

if not Path("/content/drive").is_dir():
  drive.mount("/content/drive")

####2. (1 คะแนน) Input Data

Read the data set into our working area as a ``dataframe`` named *booking*.

In [602]:
#Q.2.
dataframe = pd.read_csv("/content/drive/MyDrive/CS240/datasets/hotel_bookings.csv")
dataframe

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

###3. (10 คะแนน) Summary Information About Data Set

####3.1. (3 คะแนน) Display Summary Information
Use Python instructions to display summary information about the data set.
Basic information such as the number of rows and columns, detailed information about each column and descriptive statistical details of the data set must be displayed. Also, the first 10 rows in the data set must be shown.

In [603]:
# 3.1
nrow, ncol = dataframe.shape
print(f"number of rows: {nrow}", f"number of columns: {ncol}", sep="\n")

number of rows: 119390
number of columns: 32

In [604]:
# 3.1
print("details of each column:", dataframe.columns, sep="\n")

details of each column:
Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')

In [605]:
# 3.1
dataframe[:10]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,...,No Deposit,NaN,NaN,0,Transient,107.0,0,0,Check-Out,2015-07-03
7,Resort Hotel,0,9,2015,July,27,1,0,2,2,...,No Deposit,303.0,NaN,0,Transient,103.0,0,1,Check-Out,2015-07-03
8,Resort Hotel,1,85,2015,July,27,1,0,3,2,...,No Deposit,240.0,NaN,0,Transient,82.0,0,1,Canceled,2015-05-06
9,Resort Hotel,1,75,2015,July,27,1,0,3,2,...,No Deposit,15.0,NaN,0,Transient,105.5,0,0,Canceled,2015-04-22

In [606]:
# dataframe.isnull().values.any()
# dataframe.isnull().sum()
# dataframe.isnull().sum().sum()

####3.2 (4 คะแนน) ชุดข้อมูลนี้มีข้อมูลที่ขาดหายไป (missing values) หรือ NaN หรือไม่? ถ้ามี คอลัมน์ใดบ้างที่มีข้อมูลขาดไป จำนวนเท่าใด  อภิปรายเหตุผลประกอบคำตอบของนักศึกษา

(นักศึกษาตอบคำถามข้อ 3.2 ใน section นี้ -- ตอบเป็นภาษาไทยได้)

1. ชุดข้อมูลมี missing values
2. columns ที่ missing:
  - children
  - country
  - agent
  - company

3. total: 129425

ใช้ `dataframe.isnull().values.any()` เพื่อเช็คว่ามีค่า missing value ใน data set หรือไม่ หากมีจะ return true

จากนั้นใช้ `dataframe.isnull().sum()` เพื่อหาว่ามี columns ใดบ้างที่มี missing value

สุดท้ายใช้ `dataframe.isnull().sum().sum()` เพื่อคำนวณหาว่ามีจำนวนเท่าใด

####3.3 (3 คะแนน) เมทอดที่ให้ค่าสถิติของชุดข้อมูล (Data set) ข้างต้น คำนวณค่าสถิติทุกคอลัมน์ข้อมูลหรือไม่ อภิปรายเหตุผลประกอบด้วย

(นักศึกษาตอบคำถามข้อ 3.3 ใน section นี้ -- ตอบเป็นภาษาไทยได้)

หากถามถึงข้อ 3.2 method `.isnull().sum().sum()` คำตอบคือใช่ เนื่องจากการใช้ `.isnull().sum()` หมายถึงผลรวมจำนวนค่า NA ในแต่ละ columns และการใช้ `.sum()` อีกครั้งหนึ่งหมายถึงผลรวมจำนวนค่า NA ของแต่ละ columns ที่ได้จาก `.isnull.sum()`



---


###4. (43 คะแนน) Data Cleansing

####4.1. (38 คะแนน) Handling Missing Values

Use appropriate Python codes to accomplish the work listed in Q.4.1.1 - Q.4.1.7

##### 4.1.1. (3 คะแนน) Create a Boolean index (of the same size as the original dataframe) indicating NaN fields in the data set

[use the following code area for answering this question]

In [607]:
# Q.4.1.1.
bidx_dataframe = dataframe.isnull()
bidx_dataframe

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
119386,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
119387,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
119388,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
119389,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False


##### 4.1.2. (5 คะแนน) the number of NaN values in every column sorted descendingly (i.e. show the information corresponding to the columns with highest number of missing values first)

[use the following code area for answering this question]

In [608]:
# Q.4.1.2.
bidx_dataframe.sum().sort_values(ascending=False)

company                           112593
agent                              16340
country                              488
children                               4
arrival_date_month                     0
arrival_date_week_number               0
hotel                                  0
is_canceled                            0
stays_in_weekend_nights                0
arrival_date_day_of_month              0
adults                                 0
stays_in_week_nights                   0
babies                                 0
meal                                   0
lead_time                              0
arrival_date_year                      0
distribution_channel                   0
market_segment                         0
previous_bookings_not_canceled         0
is_repeated_guest                      0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
previous_cancellations                 0
deposit_type                           0
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

##### 4.1.3. (5 คะแนน) Is there any row in the data set with all NaNs?  Design your Python script to answer this question. Students must provide comments along your code to explain your solution.
```
Expected Output:
Number of rows with all NaNs = ..........................
```

[use the following code area for answering this question]

In [609]:
# Q.4.1.3.
# for all col in row must be null


# find all row in boolean index which all columns is True
# if all of member is True, then return the index then add to array
null_in_rows = dataframe[bidx_dataframe.all(axis=1)]

print("Number of rows with all NaNs =", len(null_in_rows))

Number of rows with all NaNs = 0

##### 4.1.4. (7 คะแนน) Fill missing values in every column (except the 'country' and 'children' column) with ``0``.
Show how you verify that all NaN values in the specified columns have been replaced.

Students must provide comments along your code to explain your solution.  

[use the following code area for answering this question]

In [610]:
# Q.4.1.4.

# init target_cols to select all columns then
# filter country and children col out of target_cols
target_cols = dataframe.columns.difference(["country", "children"])

# replace all null value in target_cols with 0 by `.fillna(0)`
dataframe[target_cols] = dataframe[target_cols].fillna(0)

# check the result with `dataframe.isnull().sum().sum()
# if result is equal to the sum of na in country + children
# determine that all of null value is replaced with 0, except for in country and children columns
print("Country's na + Children's na: ", dataframe[['country', 'children']].isnull().sum().sum())
print("Total of data frame's na: ", dataframe.isnull().sum().sum())

Country's na + Children's na:  492
Total of data frame's na:  492

##### 4.1.5. (6 คะแนน) Fill all missing values in column 'country' with the most-frequently occurred (``mode``) value of the column.

Show how you verify that all NaN values in the column 'country' have been replaced.

Students must provide comments along your code to explain your solution.

[use the following code area for answering this question]

In [611]:
# Q.4.1.5.
print("Before filling, count of country's na:", dataframe['country'].isnull().sum())
# to proof all of country's na value would replaced with mode, after filling, the count of country's na would be 0

# bring all mode of country, select for 1st mode index
# then fill all na value under country column with 1st mode value
country_mode = dataframe['country'].mode()[0]
# print(country_mode)
dataframe['country'] = dataframe['country'].fillna(country_mode)

print("After filling, count of country's na:", dataframe['country'].isnull().sum())
# the after filling result should be 0, to verify the missing data under country column is replaced

Before filling, count of country's na: 488
After filling, count of country's na: 0

#####4.1.6. (6 คะแนน) Fill all missing values in column 'children' with the rounded ``mean`` value of the column.

In [612]:
# Q.4.1.6.
# dataframe['children'].value_counts()
print("Before filling, children's na: ", dataframe['children'].isnull().sum())

children_mean = dataframe['children'].mean()
dataframe['children'] = dataframe['children'].fillna(children_mean.round())

print("After filling, children's na: ", dataframe['children'].isnull().sum())

Before filling, children's na:  4
After filling, children's na:  0

##### 4.1.7. (3 คะแนน) Change data types of columns as follows:
  * 'children' : เปลี่ยนเป็นจำนวนเต็ม (integer)
  * 'agent' : เปลี่ยนเป็นจำนวนเต็ม (integer)
  * 'company' : เปลี่ยนเป็นจำนวนเต็ม (integer)

Show how you verify that the data types have been changed as expected.

Students must provide comments along your code to explain your solution.

[use the following code area for answering this question]

In [613]:
# Q.4.1.7.
# show the data type before changing
def print_changing_dtype(status, col):
  print(f"{status} changing, data type of {col}:", dataframe[col].dtype)

print_changing_dtype("Before", "children")
print_changing_dtype("Before", "agent")
print_changing_dtype("Before", "company")

# change the dtype of given columns to int by `astype` function
dataframe = dataframe.astype({'children': int, 'agent': int, 'company': int})

print_changing_dtype("After", "children")
print_changing_dtype("After", "agent")
print_changing_dtype("After", "company")

# to verify, all of after changing's columns must be changed to int64

Before changing, data type of children: float64
Before changing, data type of agent: float64
Before changing, data type of company: float64
After changing, data type of children: int64
After changing, data type of agent: int64
After changing, data type of company: int64

##### 4.1.8. (3 คะแนน) Verify that afterwards no missing values in the data set.

Students must provide comments along your code to explain your solution.  

[use the following code area for answering this question]

In [614]:
# Q.4.1.8.

# to verify, the sum of null must be 0
dataframe.isnull().sum().sum()

np.int64(0)

####4.2. (5 คะแนน) Handling Duplicates

Use appropriate Python codes to accomplish the work listed in Q.4.2.1 - Q.4.2.2

#####4.2.1. (2.5 คะแนน) Check whether there is a duplicate in the given data set.

If any, please provide the number of duplicate rows in the given data set.

```
Expected Output:
Number of duplicate rows = ..........................
```

In [615]:
#Q.4.2.1.
dup_in_rows = dataframe[dataframe.duplicated()]
print("Number of duplicate rows =", len(dup_in_rows))

Number of duplicate rows = 32013

#####4.2.2. (2.5 คะแนน) Drop all duplicate rows found in the given data set.

Verify also that all duplicate rows have been removed.

Students must provide comments along your code to explain your solution.  

[use the following code area for answering this question]

In [616]:
#Q.4.2.2.
# to verify all of duplicated rows is dropped
# must to compare between number of duplicate rows in before and after state
dup_in_rows = dataframe[dataframe.duplicated()]
print("Before, number of duplicate rows =", len(dup_in_rows))

# use `drop_duplicates()` function to remove all duplicate data
dataframe = dataframe.drop_duplicates()

dup_in_rows = dataframe[dataframe.duplicated()]
print("After, number of duplicate rows =", len(dup_in_rows))
# success if the result show number of duplicate rows is 0

Before, number of duplicate rows = 32013
After, number of duplicate rows = 0



---

###5. (20 คะแนน) Data Validity

There are many rows in the data set that have zero guests including adults, children and babies. These type of rows does not make any sense.

Find booking rows with total guests equal to zero and remove all of them.

#####5.1.(5 คะแนน) Identify how many rows in the data set that have zero guests including adults, children and babies.

```
Expected Output:
Number of rows with total 0 guests = ..........................
```

In [617]:
#Q.5.1.

guest = ['adults', 'children', 'babies']
zero_guest = dataframe[dataframe[guest].sum(axis=1) == 0]
print("Number of rows with total 0 guests =", len(zero_guest))

Number of rows with total 0 guests = 166

#####5.2.(10 คะแนน) Identify and print all indices of rows in the data set that have zero guests including adults, children and babies.

```
Expected Output:
Indices of .... rows with total 0 guests are as follows:
<เอาท์พุตส่วนนี้ แต่ละแถวให้พิมพ์ index ของแถวที่มี total guests เป็น 0>
2224 2409 3181 3684 3708 4127 9376 31765 32029 32827
34849 37459 40392 40922 41020 41056 42452 42591 42871 42934
... เอาท์พุตถูกละไว้ ไม่ได้แสดงท้้งหมด ...
114908 115029 115091 116251 116534 117087
```

In [618]:
#Q.5.2.
print(f"Indices of {len(zero_guest)} rows with total 0 guests are as follows:", zero_guest.index)

Indices of 166 rows with total 0 guests are as follows: Index([  2224,   2409,   3181,   3684,   3708,   4127,   9376,  31765,  32029,
        32827,
       ...
       112471, 112558, 113188, 114583, 114908, 115029, 115091, 116251, 116534,
       117087],
      dtype='int64', length=166)

#####5.3.(10 คะแนน) Drop all rows in the data set that have zero guests including adults, children and babies.

Verify also that all rows with total 0 guests have been removed.

Students must provide comments along your code to explain your solution.  

<u>Hint</u>: ใช้ index ในการระบุแถวข้อมูลที่ต้องการ drop

[use the following code area for answering this question]

In [619]:
#Q.5.3.
zero_guest = dataframe[dataframe[guest].sum(axis=1) == 0]
print("Before dropping, number of 0 guest rows: ", len(zero_guest))

dataframe = dataframe.drop(zero_guest.index)

zero_guest = dataframe[dataframe[guest].sum(axis=1) == 0]
print("After dropping, number of 0 guest rows: ", len(zero_guest))
# to verify that all rows with total 0 guests have been removed,
# the retult of number of 0 guest rows after dropped must be 0

Before dropping, number of 0 guest rows:  166
After dropping, number of 0 guest rows:  0

###6. (23 คะแนน) Data Validity (More -- Challenge)

There might be some rows in the data set that there are children or baby guests without adults. These type of rows does not make any sense.

Find booking rows with such condition and remove all of them.

#####6.1.(18 คะแนน) Identify how many rows in the data set that have children or babies guests, but zero adults.

```
Expected Output:
Number of rows with children or babies guests, but zero adults = .............
```

In [620]:
#Q.6.1.
no_adult_rows = dataframe[dataframe['adults'] == 0]
no_adult_but_have_minor = no_adult_rows[ no_adult_rows[['children', 'babies']].sum(axis=1) > 0 ]
print("Number of rows with children or babies guests, but zero adults =", len(no_adult_but_have_minor))

Number of rows with children or babies guests, but zero adults = 219

#####6.2.(5 คะแนน) Drop all rows in the data set that have children or babies guests, but zero adults.

Verify also that all rows with total 0 guests have been removed.

Students must provide comments along your code to explain your solution.

In [621]:
#Q.6.2.
no_adult_rows = dataframe[dataframe['adults'] == 0]
no_adult_but_have_minor = no_adult_rows[ no_adult_rows[['children', 'babies']].sum(axis=1) > 0 ]
print("Before dropping, number of zero adult but have atlest 1 minors =", len(no_adult_but_have_minor))

dataframe = dataframe.drop(no_adult_but_have_minor.index)

no_adult_rows = dataframe[dataframe['adults'] == 0]
no_adult_but_have_minor = no_adult_rows[ no_adult_rows[['children', 'babies']].sum(axis=1) > 0 ]
print("After dropping, number of zero adult but have atlest 1 minors =", len(no_adult_but_have_minor))
# to verify all if no adult but have children or babies rows has been dropped
# the after dropping result must equal 0

Before dropping, number of zero adult but have atlest 1 minors = 219
After dropping, number of zero adult but have atlest 1 minors = 0

###7. (2 คะแนน) Save to ``csv`` file

Save the dataframe resulting from all data cleansing steps above to a csv file.

Name the file ``hotel_booking_cleaned.csv``. Be sure that we do not save the indices to csv file.

This file will be used as an input file for your next homework.

In [622]:
#Q.7.
cleaned_file_path = Path("/content/drive/MyDrive/CS240/datasets/hotel_booking_cleaned.csv")
dataframe.to_csv(cleaned_file_path)