# Pandas Basics

The well-known *Pandas* library is one of the most preferred tools for data scientists. It provides a host of useful tools, methods, and functionalities to do data manipulation and analysis. Pandas was built on  *NumPy*, the fundamental library for scientific computing in Python.

In this lecture, we will learn and understand basic Pandas. This is important for students to learn more about Pandas themselves and use Pandas to do data manipulation and analysis in the future.

This lecture includes the following topics:-

* Pandas Basic Data Structures: ``Series`` and ``DataFrame`` (#04-1)
* Read & Write from/to CSV    (#04-1)
* Read & Write from/to Excel  (#04-1)
* Retrieving Series/DataFrame Information (#04-1)  
* Data Indexing and Selection (#04-2)
* Operations in Pandas        (#04-3)

We will start our code sessions with the standard NumPy and Pandas imports:

In [ ]:
import numpy as np
import pandas as pd
#pd.__version__

# Pandas Basic Data Structures

Pandas provides a host of useful tools, methods, and functionality on top of the basic data structures, but nearly everything that follows will require an understanding of what these structures are.
Thus, before we go any further, let's introduce these two fundamental Pandas data structures: ``Series`` and ``DataFrame``.

## Pandas Series

### Pandas Series: Overview

A Pandas Series is a one-dimensional array of indexed data. It can be created from a list or array as follows:

In [ ]:
arr = np.array([0.25, 0.5, 0.75, 1.0])
arr

In [ ]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [ ]:
type(data)

The ``Series`` wraps both a sequence of *values* and a sequence of *indices*, which we can access with the ``values`` and ``index`` attributes.

![Pandas_Series](https://drive.google.com/uc?export=view&id=1bwA2IdN9c08PMjAKKeNeWcJFzJAwrpk4)

 The values are simply a familiar NumPy array:

In [ ]:
data.items()

In [ ]:
list(data.items())

In [ ]:
data.values

The index is an array-like object of type ``pd.Index``.

In [ ]:
data.index                          # equivalent to calling a function data.keys()

In [ ]:
type(data.index)

Like NumPy arrays, the Pandas series *data* can be accessed by the associated index via the familiar Python square-bracket notation:

In [ ]:
data[1]

In [ ]:
data[1:3]         # Note! the result indicates the exclusion of index 3

In [ ]:
data[:3]

In [ ]:
data[1:]

### Pandas Series: Fancy Indexing

The ``Series`` object is basically interchangeable with a one-dimensional NumPy array.
The essential difference is the presence of the index: while the Numpy Array has an *implicitly defined* integer index used to access the values, the Pandas ``Series`` has an *explicitly defined* index associated with the values.

This explicit index definition gives the ``Series`` object additional capabilities. For example, the index need not be an integer, but can consist of values of any desired type.

For example, if we wish, we can use strings as an index:

In [ ]:
# Example 1:
# Note that the default Integer indices can still be used.
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])   
data

![Pandas_Series_String_Index_1](https://drive.google.com/uc?export=view&id=16IZx43YKn-sY8yOxqMitNnqAsEBt1siY)

In [ ]:
data.values

In [ ]:
data.index  # equivalent to calling the function data.keys()

In [ ]:
data['a']

In [ ]:
# Example 2:
# Note that the default Integer indices can still be used.
months = pd.Series([31, 28, 31, 30, 31],
                   index=['jan', 'feb', 'mar', 'apr', 'may'])

![Pandas_Series_String_Index_1](https://drive.google.com/uc?export=view&id=1IA9MwXG9QgLR6T5lk6lZlMu_lbP_D7tz)

In [ ]:
months.index

In [ ]:
months

In [ ]:
months[4]

In [ ]:
months['may']

We can even use non-contiguous or non-sequential indices:

In [ ]:
# Example 3: 
# Note that the default Integer indices are overruled and cannot be used
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7])
data

![Pandas_Series_String_Index_1](https://drive.google.com/uc?export=view&id=1RpaszqVV07jWV4gdSffZ0osK_wUeaK2w)

In [ ]:
data.index

In [ ]:
data[3]

In [ ]:
# Example 4:
# Note that the default Integer indices are overruled and cannot be used
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[10, 20, 30, 40], name='mydata')
data

![Pandas_Series_String_Index_1](https://drive.google.com/uc?export=view&id=1qf_jAtQLneOehGVUdBVKT9Ztx2QWQhAE)

In [ ]:
data.index

In [ ]:
# Try running the following two lines, which one will cause an error
data[10]
data[0]

### Pandas Series: Constructing ``Series`` Objets from Dictionaries

The ``Series``-as-dictionary analogy can be made even more clear by constructing a ``Series`` object directly from a Python dictionary:

In [ ]:
# By default, a Series will be created 
# where the 'index' is drawn from the sorted dictionary keys
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict) 
population

In [ ]:
population.index

In [ ]:
population['New York']

Unlike a dictionary, the Series also supports array-style operations such as slicing:

Please note the inclusion of 'Florida' in the slice.

In [ ]:
population[1:3]

In [ ]:
population['Texas':'Florida']

---
Exercise: test your understanding about Pandas Series: Slicing using default and explicit indices

Given the $fruits$ ``Pandas Series`` shown below, 
what will be the results of the following three lines of code? 

1.   fruits['f']
2.   fruits[1:4]
3.   fruits['b':'e']

In [ ]:
fruits = pd.Series(['apple', 'banana', 'cantaloupe', 'durian', 'eggplant', 'figs', 'grapefruit'], index=list('abcdefg'))
fruits

In [ ]:
#2
fruits[1:4]

In [ ]:
#3
fruits['b':'e']

---

## Pandas DataFrame

***
A two dimensional labeled data structure with columns of potentially different types.
***

The next fundamental structure in Pandas is the ``DataFrame``.
If a ``Series`` is an analog of a *one-dimensional array* with flexible indices, a ``DataFrame`` is an analog of a *two-dimensional array* with both flexible row indices and flexible column names. 

Just as you might think of a two-dimensional array as an ordered sequence of aligned one-dimensional columns, you can think of a ``DataFrame`` as a sequence of aligned ``Series`` objects. Here, by "aligned" we mean that they share the same index.

![Pandas_Series_vs_DataFrame](https://drive.google.com/uc?export=view&id=1mLxj8kI7pzBnSCO12VpTrTHB4yJGN-Io)

To demonstrate this, let's first construct a new Series listing the area of each of the five states discussed in the previous section:

---
I. Creating a ``DataFrame`` from three separate ``Series``
---

In [ ]:
# Recall, the population 'series' from the previous section
population

In [ ]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

In [ ]:
county_dict = {'California': 58, 'Texas': 254, 'New York': 62,
               'Florida': 67, 'Illinois': 152}
county =  pd.Series(county_dict)
county

In [ ]:
states = pd.DataFrame({'population': population,
                       'area': area,
                       'county': county})
states

            population    area  county
California    38332521  423967      58
Texas         26448193  695662     254
New York      19651127  141297      62
Florida       19552860  170312      67
Illinois      12882135  149995     152

In [ ]:
states.columns

Index(['population', 'area', 'county'], dtype='object')

In [ ]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

![Pandas_Series_String_Index_1](https://drive.google.com/uc?export=view&id=1nqZk8LOiY-dU_g5eSxWShTkTF2rDT7Xw)

---
II. Creating a ``DataFrame`` from a ``Dictionary``
---

In [ ]:
state_dict = {'population': [38332521, 26448193, 19651127, 19552860, 12882135],
              'area':       [423967,   695662,   141297,   170312,   149995],
              'county':     [58,       254,      62,       67,       152]}
#states = pd.DataFrame(state_dict)
states = pd.DataFrame(state_dict, 
                      index=['California', 'Texas', 'New York', 'Florida', 'Illinois'])
states

In [ ]:
import pandas as pd
state_dict_full = {'state':      ['California', 'Texas', 'New York', 'Florida', 'Illinois'],
                   'population': [38332521, 26448193, 19651127, 19552860, 12882135],
                   'area':       [423967,   695662,   141297,   170312,   149995],
                   'county':     [58,       254,      62,       67,       152]}
states = pd.DataFrame(state_dict_full)
states = states.set_index('state')    # set the column 'state' as index of this dataframe
states

            population    area  county
state
California    38332521  423967      58
Texas         26448193  695662     254
New York      19651127  141297      62
Florida       19552860  170312      67
Illinois      12882135  149995     152

---
III. Creating a ``DataFrame`` from a ``List``
---

In [ ]:
# [population, area, county]
# Note: state_info_list is a list of 5 sub-lists
state_info_list = [[38332521, 423967, 58],
                   [26448193, 695662, 254],
                   [19651127, 141297, 62],
                   [19552860, 170312, 67],
                   [12882135, 149995, 152]]
              
states = pd.DataFrame(state_info_list)
#states = pd.DataFrame(state_info_list, columns=['population', 'area', 'county'])
#states = pd.DataFrame(state_info_list, columns=['population', 'area', 'county'], index=['California', 'Texas', 'New York', 'Florida', 'Illinois'])
states

---
Exercise: Try creating a dataframe as shown in the figure below.
---
![Pandas_Series_vs_DataFrame](https://drive.google.com/uc?export=view&id=15_g-HE8aaGVOyEJ03uNOSkG77qEPPeQN)

In [ ]:
# Use this area to work on the exercise

---

# Retrieving Series/DataFrame Information

In [ ]:
import pandas as pd
# create a Series called 'data'
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])   
data

In [ ]:
# create a DataFrame called 'states'
state_dict = {'population': [38332521, 26448193, 19651127, 19552860, 12882135],
              'area':       [423967,   695662,   141297,   170312,   149995],
              'county':     [58,       254,      62,       67,       152]}
states = pd.DataFrame(state_dict, 
                      index=['California', 'Texas', 'New York', 'Florida', 'Illinois'])
states

            population    area  county
California    38332521  423967      58
Texas         26448193  695662     254
New York      19651127  141297      62
Florida       19552860  170312      67
Illinois      12882135  149995     152

In [ ]:
states.shape            # (#rows, #columns)
#data.shape             # applied to Series

In [ ]:
states.index            # describe 'indices' of the dataframe
#data.index             # applied to Series

In [ ]:
states.columns          # desribe 'columns' of the dataframe

In [ ]:
states.info()           # describe the general information of the dataframe

In [ ]:
states.count()          # number of non-null cells in each column of the dataframe
#data.count()

population    5
area          5
county        5
dtype: int64

# Input/Output 

Read & Write from/to Files


*   Read & Write from/to CSV
*   Read & Write from/to Excel

___
Read & Write from/to CSV
___

In [ ]:
import pandas as pd

# read from a csv file located in your google drive folder
cal_house = pd.read_csv("./msleep.csv")
cal_house

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [ ]:
cal_house.info()

In [ ]:
# write the mentioned dataframe 'states' to a csv file located in your google drive folder
states.to_csv("./state.csv")

___
Read & Write from/to Excel
___

In [ ]:
import pandas as pd

# read the first sheet from the xlsx file "example.xlsx" into a dataframe
#df = pd.read_excel("example.xlsx")

# write the mentioned dataframe 'states' to an excel file in your google drive folder
# the sheetname is also specified
states.to_excel("/content/drive/MyDrive/Classroom_from_TU-GDrive/CS245_64-1 870001_650001/data/output/states.xlsx", sheet_name="states")